In [152]:
import numpy as np

In [153]:
n = np.array([1,2,3,4]) #converting the python list to a Numpy Array

In [154]:
n

array([1, 2, 3, 4])

In [155]:
n.tolist() #converting the numpy array to a list

[1, 2, 3, 4]

In [156]:
np.arange(1, 11, 1) #step size=1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
np.linspace(1, 100, 4) # 4 numbers with equal distance

array([  1.,  34.,  67., 100.])

In [158]:
np.zeros((3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [159]:
np.ones((3,3), dtype=np.float16)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [160]:
np.empty((3,4), dtype = np.int8) #creates an empty array with random values

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [161]:
np.full((3,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [162]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [163]:
np.eye(2,3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0]], dtype=int8)

In [164]:
np.random.rand(4,3)

array([[0.01466946, 0.25208034, 0.12503951],
       [0.11471855, 0.51375566, 0.75552378],
       [0.32293902, 0.55068106, 0.87084286],
       [0.15298496, 0.31202914, 0.26739269]])

## Numpy Array Attributes

In [165]:
ar = np.array([[1,2,3], [4,5,6]])

In [166]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
ar.shape

(2, 3)

In [168]:
ar.ndim

2

In [169]:
ar.size

6

In [170]:
ar.dtype

dtype('int64')

In [171]:
ar.itemsize

8

In [172]:
ar.nbytes

48

In [173]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Array Reshaping and Resizing in Numpy

In [174]:
a = np.array([1,2,3,4,5,6])

In [175]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [177]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [178]:
a.reshape(-1,2) # -1 means the possible value that will will be given by Numpy in one dimension

array([[1, 2],
       [3, 4],
       [5, 6]])

In [179]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
b = np.array([[1,2,3],[4,5,6]])

In [181]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [182]:
b.ndim

2

In [183]:
print(b.shape)
print(b.size)

(2, 3)
6


In [184]:
new_view_b = b.ravel() #creates a new 1D view but the new_view_b object also points to the same address as object b

In [185]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
new_view_b

array([1, 2, 3, 4, 5, 6])

In [187]:
b[0][1] = 8

In [188]:
b

array([[1, 8, 3],
       [4, 5, 6]])

In [189]:
new_view_b

array([1, 8, 3, 4, 5, 6])

In [190]:
c = np.array([[3,2,9], [6,1,7]])

In [191]:
d = c.flatten()

In [192]:
d

array([3, 2, 9, 6, 1, 7])

In [193]:
c[0][2] = 5

In [194]:
c

array([[3, 2, 5],
       [6, 1, 7]])

In [195]:
d # has copied and created a data in a different memory location. Converts into a 1D array. But changes in object c will not affect object d

array([3, 2, 9, 6, 1, 7])

In [196]:
c.resize((3,3), refcheck=False)

In [197]:
c

array([[3, 2, 5],
       [6, 1, 7],
       [0, 0, 0]])

In [198]:
e = np.array([[[1], [2], [3]]])

In [199]:
e.ndim

3

In [200]:
e.squeeze()

array([1, 2, 3])

In [201]:
e.size

3

In [202]:
e.shape

(1, 3, 1)

## Arrays Indexing and Slicing

In [203]:
f = np.array([1,2,3,4,5,6,7,8,9,10])

In [204]:
f[0]

np.int64(1)

In [205]:
print(f[0])

1


In [206]:
print(f[-1])

10


In [207]:
print(f[-2])

9


In [208]:
print(f[1:7])

[2 3 4 5 6 7]


In [209]:
print(f[1:7:2])

[2 4 6]


In [210]:
print(f[0:9])

[1 2 3 4 5 6 7 8 9]


In [211]:
print(f[1:9])

[2 3 4 5 6 7 8 9]


In [216]:
f[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [217]:
f[::2]

array([1, 3, 5, 7, 9])

In [218]:
f[::-2]

array([10,  8,  6,  4,  2])