In [10]:
import numpy as np

In [11]:
n = np.array([1,2,3,4]) #converting the python list to a Numpy Array

In [12]:
n

array([1, 2, 3, 4])

In [13]:
n.tolist() #converting the numpy array to a list

[1, 2, 3, 4]

In [16]:
np.arange(1, 11, 1) #step size=1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1, 100, 4) # 4 numbers with equal distance

array([  1.,  34.,  67., 100.])

In [18]:
np.zeros((3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [19]:
np.ones((3,3), dtype=np.float16)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [ ]:
np.empty((3,4), dtype = np.int8) #creates an empty array with random values

array([[ -1, 123,  -1,  -5],
       [  0,  64,   0,  20],
       [  0,   4,   1,   0]], dtype=int8)