In [2]:
import numpy as np

In [3]:
n = np.array([1,2,3,4]) #converting the python list to a Numpy Array

In [4]:
n

array([1, 2, 3, 4])

In [5]:
n.tolist() #converting the numpy array to a list

[1, 2, 3, 4]

In [6]:
np.arange(1, 11, 1) #step size=1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.linspace(1, 100, 4) # 4 numbers with equal distance

array([  1.,  34.,  67., 100.])

In [8]:
np.zeros((3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [9]:
np.ones((3,3), dtype=np.float16)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [10]:
np.empty((3,4), dtype = np.int8) #creates an empty array with random values

array([[ -1, 123,  -1,  -5],
       [  0,  64,   0,  20],
       [  0,   4,   1,   0]], dtype=int8)

In [11]:
np.full((3,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(2,3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0]], dtype=int8)

In [14]:
np.random.rand(4,3)

array([[0.50566804, 0.02018712, 0.95682759],
       [0.3591966 , 0.31085103, 0.75949814],
       [0.28305226, 0.11744124, 0.02361767],
       [0.52422631, 0.34091431, 0.195347  ]])

## Numpy Array Attributes

In [15]:
ar = np.array([[1,2,3], [4,5,6]])

In [16]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
ar.shape

(2, 3)

In [18]:
ar.ndim

2

In [19]:
ar.size

6

In [20]:
ar.dtype

dtype('int64')

In [21]:
ar.itemsize

8

In [22]:
ar.nbytes

48

In [23]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Array Reshaping and Resizing in Numpy

In [24]:
a = np.array([1,2,3,4,5,6])

In [25]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [28]:
a.reshape(-1,2) # -1 means the possible value that will will be given by Numpy in one dimension

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b = np.array([[1,2,3],[4,5,6]])

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b.ndim

2

In [33]:
print(b.shape)
print(b.size)

(2, 3)
6


In [34]:
new_view_b = b.ravel() #creates a new 1D view but the new_view_b object also points to the same address as object b

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
new_view_b

array([1, 2, 3, 4, 5, 6])

In [37]:
b[0][1] = 8

In [38]:
b

array([[1, 8, 3],
       [4, 5, 6]])

In [39]:
new_view_b

array([1, 8, 3, 4, 5, 6])

In [40]:
c = np.array([[3,2,9], [6,1,7]])

In [41]:
d = c.flatten()

In [42]:
d

array([3, 2, 9, 6, 1, 7])

In [43]:
c[0][2] = 5

In [44]:
c

array([[3, 2, 5],
       [6, 1, 7]])

In [45]:
d # has copied and created a data in a different memory location. Converts into a 1D array. But changes in object c will not affect object d

array([3, 2, 9, 6, 1, 7])

In [46]:
c.resize((3,3), refcheck=False)

In [47]:
c

array([[3, 2, 5],
       [6, 1, 7],
       [0, 0, 0]])

In [48]:
e = np.array([[[1], [2], [3]]])

In [49]:
e.ndim

3

In [50]:
e.squeeze()

array([1, 2, 3])

In [51]:
e.size

3

In [52]:
e.shape

(1, 3, 1)

## Arrays Indexing and Slicing

In [53]:
f = np.array([1,2,3,4,5,6,7,8,9,10])

In [54]:
f[0]

np.int64(1)

In [55]:
print(f[0])

1


In [56]:
print(f[-1])

10


In [57]:
print(f[-2])

9


In [58]:
print(f[1:7])

[2 3 4 5 6 7]


In [59]:
print(f[1:7:2])

[2 4 6]


In [60]:
print(f[0:9])

[1 2 3 4 5 6 7 8 9]


In [61]:
print(f[1:9])

[2 3 4 5 6 7 8 9]


In [62]:
f[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [63]:
f[::2]

array([1, 3, 5, 7, 9])

In [64]:
f[::-2]

array([10,  8,  6,  4,  2])

### Indexing in 2D Arrays

In [65]:
a = np.array([[1,2,3],
              [4,5,6]])

In [66]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
a[0][1]

np.int64(2)

In [68]:
print(a[0][1])

2


In [69]:
# can be read as
print(a[0,1])

2


In [70]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [71]:
a[:,2]

array([3, 6, 9])

In [72]:
print(a[:,2])

[3 6 9]


In [75]:
a[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [76]:
a[1:, 1:]

array([[5, 6],
       [8, 9]])

In [77]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [78]:
a[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])