In [10]:
import numpy as np

In [11]:
n = np.array([1,2,3,4]) #converting the python list to a Numpy Array

In [12]:
n

array([1, 2, 3, 4])

In [13]:
n.tolist() #converting the numpy array to a list

[1, 2, 3, 4]

In [16]:
np.arange(1, 11, 1) #step size=1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1, 100, 4) # 4 numbers with equal distance

array([  1.,  34.,  67., 100.])

In [18]:
np.zeros((3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [19]:
np.ones((3,3), dtype=np.float16)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [ ]:
np.empty((3,4), dtype = np.int8) #creates an empty array with random values

array([[ -1, 123,  -1,  -5],
       [  0,  64,   0,  20],
       [  0,   4,   1,   0]], dtype=int8)

In [21]:
np.full((3,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(2,3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0]], dtype=int8)

In [29]:
np.random.rand(4,3)

array([[0.75759656, 0.37971033, 0.88841415],
       [0.29005463, 0.58955764, 0.3522659 ],
       [0.08196117, 0.27503368, 0.67800722],
       [0.33011796, 0.75209807, 0.66278561]])

## Numpy Array Attributes

In [30]:
ar = np.array([[1,2,3], [4,5,6]])

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
ar.shape

(2, 3)

In [33]:
ar.ndim

2

In [34]:
ar.size

6

In [36]:
ar.dtype

dtype('int64')

In [37]:
ar.itemsize

8

In [38]:
ar.nbytes

48

In [39]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Array Reshaping and Resizing in Numpy

In [40]:
a = np.array([1,2,3,4,5,6])

In [41]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a.reshape(-1,2) # -1 means the possible value that will will be given by Numpy in one dimension

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
b = np.array([[1,2,3],[4,5,6]])

In [47]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b.ndim

2

In [50]:
print(b.shape)
print(b.size)

(2, 3)
6


In [ ]:
new_view_b = b.ravel() #creates a new 1D view but the new_view_b object also points to the same address as object b

In [55]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
new_view_b

array([1, 2, 3, 4, 5, 6])

In [57]:
b[0][1] = 8

In [58]:
b

array([[1, 8, 3],
       [4, 5, 6]])

In [59]:
new_view_b

array([1, 8, 3, 4, 5, 6])

In [60]:
c = np.array([[3,2,9], [6,1,7]])

In [61]:
d = c.flatten()

In [62]:
d

array([3, 2, 9, 6, 1, 7])

In [65]:
c[0][2] = 5

In [66]:
c

array([[3, 2, 5],
       [6, 1, 7]])

In [68]:
d # has copied and created a data in a different memory location. Converts into a 1D array. But changes in object c will not affect object d

array([3, 2, 9, 6, 1, 7])

In [70]:
c.resize((3,3), refcheck=False)

In [71]:
c

array([[3, 2, 5],
       [6, 1, 7],
       [0, 0, 0]])

In [76]:
e = np.array([[[1], [2], [3]]])

In [77]:
e.ndim

3

In [74]:
e.squeeze()

array([1, 2, 3])

In [78]:
e.size

3

In [79]:
e.shape

(1, 3, 1)