In [10]:
import numpy as np

In [11]:
n = np.array([1,2,3,4]) #converting the python list to a Numpy Array

In [12]:
n

array([1, 2, 3, 4])

In [13]:
n.tolist() #converting the numpy array to a list

[1, 2, 3, 4]

In [16]:
np.arange(1, 11, 1) #step size=1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1, 100, 4) # 4 numbers with equal distance

array([  1.,  34.,  67., 100.])